# Generated by Django 3.0.3 on 2020-03-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedb',
            name='category',
            field=models.CharField(choices=[('unknown', 'unknown'), ('Animal', 'Animal'), ('Fruit', 'Fruit'), ('Nature', 'Nature'), ('Art', 'Art')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='imagedb',
            name='imagefile',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
