# Generated by Django 3.0.3 on 2020-03-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImgHub', '0002_auto_20200307_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagedb',
            old_name='imagefile',
            new_name='image_file',
        ),
    ]
