# Generated by Django 2.2 on 2020-04-18 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImgHub', '0002_imagedb_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedb',
            name='user',
            field=models.ForeignKey(null='Admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
