# Generated by Django 2.2 on 2020-04-18 23:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ImgHub', '0003_auto_20200419_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedb',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 23, 35, 36, 102013, tzinfo=utc)),
        ),
    ]
