# Generated by Django 2.2 on 2020-03-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImgHub', '0004_auto_20200323_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagedb',
            old_name='category',
            new_name='u_ctg',
        ),
    ]
