# Generated by Django 2.2 on 2020-04-21 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ImgHub', '0006_auto_20200421_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedb',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagedb',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 14, 3, 0, 493426, tzinfo=utc)),
        ),
    ]
